.PHONY: clean All

All:
	@echo "----------Building project:[ Week_1_Opdracht_10 - Debug ]----------"
	@cd "Week_1_Opdracht_10" && "$(MAKE)" -f  "Week_1_Opdracht_10.mk"
clean:
	@echo "----------Cleaning project:[ Week_1_Opdracht_10 - Debug ]----------"
	@cd "Week_1_Opdracht_10" && "$(MAKE)" -f  "Week_1_Opdracht_10.mk" clean
